### PR TITLE
fix: support rxjs lettable operators

### LINKED ISSUE #247: RxJS: lettable operators
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

Need to check / verify whether RxJS "lettable operators" do work by default.

2017-11-03 10_31_56-version 5 0 0 of angular now available angular blog

https://blog.angular.io/version-5-0-0-of-angular-now-available-37e414935ced

#### How To Reproduce

see above

#### Expected Behaviour

see above, lettable operators should work ootb

#### Version Information

```
ng-packagr: v1.5.0-rc.x
```

### PR DESCRIPTION
**Pull request by ocombe**
## I'm submitting a...

```
[x] Bug Fix
```

## Description
I've updated the list of externals for rxjs to support lettable operators. Tested on my lib (ngx-translate) and it works.

Fixes #247

Before:
screenshot-2017-11-23 dist bundles core umd min js - source map explorer

After:
screenshot-2017-11-23 dist bundles core umd min js - source map explorer

## Does this PR introduce a breaking change?

```
[x] No
```

### CODE REVIEW

**Comment by ClemensSchneider** [comment]
Tested adding externals to local ng-package.json and it removes almost all rxjs dependencies from the bundle, thanks!

Some remain though and I think it is related to an import of the `animationFrame` scheduler:

`import { animationFrame } from 'rxjs/scheduler/animationFrame';`

Is there any additional declaration required to match this one, too? I can't really figure out how to declare it.

**Comment by ocombe** [comment]
try that and let me know if it works:

```js
'rxjs/scheduler/Action': 'Rx.Scheduler',
'rxjs/scheduler/animationFrame': 'Rx.Scheduler',
'rxjs/scheduler/AnimationFrameAction': 'Rx.Scheduler',
'rxjs/scheduler/asap': 'Rx.Scheduler',
'rxjs/scheduler/AsapAction': 'Rx.Scheduler',
'rxjs/scheduler/async': 'Rx.Scheduler',
'rxjs/scheduler/AsyncAction': 'Rx.Scheduler',
'rxjs/scheduler/AsyncScheduler': 'Rx.Scheduler',
'rxjs/scheduler/queue': 'Rx.Scheduler',
'rxjs/scheduler/QueueAction': 'Rx.Scheduler',
'rxjs/scheduler/QueueScheduler': 'Rx.Scheduler',
'rxjs/scheduler/VirtualTimeScheduler': 'Rx.Scheduler',
'rxjs/scheduler': 'Rx.Scheduler',
```

**Comment by ClemensSchneider** [comment]
Works, big thanks!

**Comment by ocombe** [comment]
And you tested that the lib works too, right? Not just that it removes the code from the bundle

**Comment by ClemensSchneider** [comment]
Tested and works, yes.

**Comment by ocombe** [comment]
Perfect, thanks!
I've updated the PR to add this

**Comment by dherges** [comment]
Good work from you all!

I am just into a meeting ... will look later to merge / release :-) 

Cheers, David

**Comment by dherges** [comment]
RxJS Lettable Operators Usage Guide: https://github.com/ReactiveX/rxjs/blob/master/doc/lettable-operators.md#lettable-operators

**Comment by ocombe** [comment]
Oh look at this from the docs:
```
If you require('rxjs/_esm5/path-mapping'), you will receive a function that returns an object of key-value pairs mapping each input to it's file location on disk. Utilize this mapping as follows:

webpack.config.js

Simple configuration:

const rxPaths = require('rxjs/_esm5/path-mapping');
const webpack = require('webpack');
const path = require('path');

module.exports = {
  entry: 'index.js',
  output: 'bundle.js',
  resolve: {
    // Use the "alias" key to resolve to an ESM distribution
    alias: rxPaths()
  },
  plugins: [
    new webpack.optimize.ModuleConcatenationPlugin()
  ]
};
```

This would work with rollup too

**Comment by dherges** [comment]
Hi @ocombe,

I don't understand. The mappings are

```json
"rxjs/observable/concat": path.resolve(PATH_REPLACEMENT, "rxjs/_esm5/observable/concat.js")
```

For rollup, we need a mapping to the UMD identifier. So when requiring the `rxPaths()` I look up filenames which doesn't help with rollup or am I missing somethng?

**Comment by ocombe** [comment]
Ah maybe, I haven't tried actually :)

**Pull request merged**
