### PR TITLE
fix: depend on user's typescript and tsc-wrapped

### PR DESCRIPTION
**Pull request by dherges**
## I'm submitting a...

```
[x] Bug Fix
[ ] Feature
[ ] Other (Refactoring, Added tests, Documentation, ...)
```

## Checklist

- [x] Commit Messages follow the [Conventional Commits](https://conventionalcommits.org/) pattern
  - A feature commit message is prefixed "feat:"
  - A bugfix commit message is prefixed "fix:"
- [ ] Tests for the changes have been added

## Description

Previously, a user of ng-packagr could install an incompatible typescript version for ng-packagr. Prevent inadvertent typescript installs by depending on a user's typescript isntallation (peerDependencies). Same for tsc-wrapped.

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by jeffora** [comment]
Hey, I know this is already merged, but I just wanted to mention that this change *is* a breaking change. In a CI scenario where a package depends on `"ng-packagr": "^1.0.0"` or `"ng-packagr": "~1.5.0"`, the build can break with no other code changes.

If `1.5.1` is installed, and the project including this doesn't include `@angular/tsc-wrapped`, `ng-packagr` will fail to run. The exact same project would have run with no issues at all on `1.5.0`.

**Comment by dherges** [comment]
@jeffora Understand. For `typescript` this is not an issue because ~almost~ every Angular project will have typescript in their `devDependencies` and thus it was already installed to `node_modules/typescript`. `@angular/tsc-wrapped`, and the Angular core team said it was an internal package, was probably never hoisted to a direct child of `node_modules` but kept further down tree.... hmpf.

Sorry about that. I should've planned the release better by collecting the breaking changes for 2.x release candidates and incrementally improving that towards Angular 5 support.... :/

**Comment by dherges** [comment]
- Create branch `v1` starting from tag `v1.5.1`
- revert commit 42b2f08
- re-apply change for `typescript` as `peerDependency`
- release `v1.5.2`
- cherry-pick 4068664 (feat) on branch `v1`
- release `v1.6.0` w/ Angular v4 support only

At that point, `v1.x` releases are finished.

Go back to `master`, manually copy&paste the changelog, manually release a `2.0.0-rc.0` (which needs to be npm-tagged `next`).

Does that sound good?

I'm curious why at vmware/clarity there were no issues as somehow tsc-wrapped has hoisted to node_modules for them?!?

**Comment by jeffora** [comment]
Thanks for responding @dherges. That fix sounds viable to me, but we're also ok at the moment just pinning to 1.4.x.

Perhaps vmware/clarity had tsc-wrapped installed as a devDependency or similar in root projects?

**Pull request merged**
