### PR TITLE
feat: add ‘preserveWhitespaces’ to tsconfig

### PR DESCRIPTION
**Pull request by alan-agius4**
## I'm submitting a...

```
[ ] Bug Fix
[x ] Feature
[ ] Other (Refactoring, Added tests, Documentation, ...)
```

## Checklist

- [ ] Commit Messages follow the [Conventional Commits](https://conventionalcommits.org/) pattern
  - A feature commit message is prefixed "feat:"
  - A bugfix commit message is prefixed "fix:"
- [ ] Tests for the changes have been added

## Description

"preserveWhitespaces"
Whether to remove blank text nodes from compiled templates. This option is true by default.

It is recommended to set this to explicitly to false as it emits smaller template factory modules and might be set to false by default in the future.

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by dherges** [comment]
Yes, atm, I'd prefer the programmatic API approach for overriding the tsconfig. We'll let the default for `preserveWhitespaces: true` and then people can override on a per-component (per-module?) basis or through the programmatic API

**Comment by deebloo** [comment]
You can also set it when you bootstrap your module

**Comment by dherges** [comment]
Adding to my previous comment, setting by default to false will also subtetly break existing library builds in the case where a whitespace in the HTML template is relevant to layouting / stylesheet.

**Comment by mkoczka** [comment]
@dherges Is there actually some way to set preserveWhitespaces to false in the library? Setting it directly on component doesn't work for me.

Final build still does the whitespaces included and also app that is using this library doesn't get rid of the library whitespaces.

**Comment by dherges** [comment]
Like this?

https://www.softwarearchitekt.at/post/2017/08/31/clever-white-space-handling-for-better-performance-in-angular-5.aspx

```
@Component({
  selector: 'app-passenger-search',
  templateUrl: './passenger-search.component.html',
  styleUrls: ['./passenger-search.component.css'],
  preserveWhitespaces: false
})
export class PassengerSearchComponent  {
}
```

**Comment by mkoczka** [comment]
I know how to set it, but it doesn't work when I include the final library bundle to my app.

**Comment by mkoczka** [comment]
I know how to set it, but it doesn't work. I can reproduce it on demo ng-packaged repository. I forked it [here](https://github.com/mkoczka/ng-packaged).

in foo.component.ts
```
@Component({
  selector: 'my-foo',
  template: '<h1> foo </h1>',
  styleUrls: ['./foo.component.scss'],
  preserveWhitespaces: false
})
export class FooComponent {
}
```

When I build the library with `npm run build:lib` and include it as a package into fresh angular-cli generated app. It still has the whitespaces in `<h1> foo </h1>` whether I have preserveWhitespaces set to true or false in the application.

**Comment by dherges** [comment]
@mkoczka This pull request is a bad place to discuss the issue. Can you make sure whether `ngc -p <...>` on your source code works as intended and then either open an issue on this project or on the angular github project?

**Comment by mkoczka** [comment]
@dherges sure

**Pull request closed without merging**
