### PR TITLE
fix: support require() of .json files by rollup

### PR DESCRIPTION
**Pull request by sumigoma**
## I'm submitting a...

```
[X] Bug Fix
[ ] Feature
[ ] Other (Refactoring, Added tests, Documentation, ...)
```

## Checklist

- [X] Commit Messages follow the [Conventional Commits](https://conventionalcommits.org/) pattern
  - A feature commit message is prefixed "feat:"
  - A bugfix commit message is prefixed "fix:"
- [ ] Tests for the changes have been added

Not sure where the tests should go for this.

## Description

Adding rollup-plugin-json as a dependency to resolve exceptions around require()-ing .json files. I noticed this issue within a third-party library (moment-timezone) that internally had a require(___.json) statement and was throwing an exception, but there appears to be another issue like this here -
https://github.com/dherges/ng-packagr/issues/325.

## Does this PR introduce a breaking change?

```
[ ] Yes
[X] No
```

### CODE REVIEW

**Comment by DavidParks8** [comment]
Can you please add tests for this fix?

**Comment by sumigoma** [comment]
@DavidParks8 Sure, but I was wondering where would be the best place to put the test... Would `integration/samples` make sense? Should I create a new folder under that, or put it into one of the existing samples? Is it really an integration test?

**Comment by DavidParks8** [comment]
Whether or not it's an integration test, the integration/samples folder is what we have available for testing. I would leave it up to @dherges to decide where he wants the test, as it is ultimately his decision on whether or not the PR gets merged.

**Comment by dherges** [comment]
Hi @sumigoma,

the build fails because of the lock file:

```
error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.
```

Can you `yarn add rollup-plugin-json` and then commit the lockfile to PR?

**Comment by sumigoma** [comment]
@ng-packagr, Yes, I noticed the failure and figured I'd resolve it when I got around to writing the tests.

**Comment by sumigoma** [comment]
whoops, I meant @dherges

**Comment by sumigoma** [comment]
@dherges I have a branch called `rollup-plugin-json` in my fork, where I added a test under `integration/samples/secondary/json`. https://github.com/sumigoma/ng-packagr/tree/rollup-plugin-json/integration/samples/secondary/json

But what's odd is that after building this updated sample, I do not see the contents of the test.json file in the output in the `dist` folder. Am I missing something in the configuration to get rollup to pickup the `require('./test.json')` and incorporate it into the resulting bundles?

**Comment by sumigoma** [comment]
@dherges The original issue seems to have been addressed somehow in ng-packagr@2.0.0-rc.9. Closing as `rollup-plugin-json` no longer appears to be necessary. Thanks.

**Pull request closed without merging**
