### PR TITLE
feat: remove unused `dependencies` and update `peerDependencies`

### PR DESCRIPTION
**Pull request by alan-agius4**
## I'm submitting a...

```
[ ] Bug Fix
[x] Feature
[ ] Other (Refactoring, Added tests, Documentation, ...)
```

## Checklist

- [x] Commit Messages follow the [Conventional Commits](https://conventionalcommits.org/) pattern
  - A feature commit message is prefixed "feat:"
  - A bugfix commit message is prefixed "fix:"
- [ ] Tests for the changes have been added

## Description

- removed `lodash`, `glob` and `read-file` from dependencies
- removed `@types/glob`, `@types/lodash` from `devDependencies`
- bumped `@angular/cdk`, `tsickle` and `typescript`
- updated `peerDependencies` `tsickle` to `^0.25.0` and `typescript` to `>=2.4.2 <2.6`

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by dherges** [comment]
But `glob` is being used? 

https://github.com/dherges/ng-packagr/blob/master/src/lib/steps/init.ts#L3

**Comment by alan-agius4** [comment]
missed that, will fix it asap

**Comment by alan-agius4** [comment]
good spot, fixed

**Comment by dherges** [comment]
peerDep: `tsickle: ^0.24.0` – aligned with `@angular/compiler-cli: ^5.0.0`

**Comment by dherges** [comment]
see https://github.com/angular/angular/blob/5.0.0/packages/compiler-cli/package.json#L14

**Comment by alan-agius4** [comment]
But for angular 5.1.x its 0.25.5
https://github.com/angular/compiler-cli-builds/blob/master/package.json

So probably it should be
>=0.24 < 0.26

**Comment by dherges** [comment]
I think it's ok with the "^0.25.0"

**Comment by alan-agius4** [comment]
Okay i’ll update it soon

**Comment by dherges** [comment]
Sorry, meant `^0.24.0` ➡️  People on 5.0.x use `compiler-cli: ~5.0.0` and `tsickle: >=0.24.0 <0.3.0` and people on 5.1.x use `compiler-cli: ~5.1.0` and `tsickle: ^0.25.5`

**Comment by alan-agius4** [comment]
Bur when you specify  ^0.24.0 it means ~0.24.X do its not correct

Since there is no major verion of tsickle npm treats ^ as ~

http://semver.org/

**Comment by alan-agius4** [comment]
Take a look here:

http://jubianchi.github.io/semver-check/

**Comment by dherges** [comment]
Ok, then it should be `tsickle: ">=0.24.0 <0.26.0"` right?

**Comment by alan-agius4** [comment]
Yes :) sry for the whole back and forth

**Pull request merged**
