### PR TITLE
fix: update node-sass to v4.9.3

### PR DESCRIPTION
**Pull request by Sibiraj-S**
## I'm submitting a...

```
[x] Bug Fix
[ ] Feature
[ ] Other (Refactoring, Added tests, Documentation, ...)
```

## Checklist

- [x] Commit Messages follow the [Conventional Commits](https://conventionalcommits.org/) pattern
  - A feature commit message is prefixed "feat:"
  - A bugfix commit message is prefixed "fix:"
- [ ] Tests for the changes have been added

## Description

Updates Node Sass to v4.9.3 which removes vulnerability warnings while installing the package

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by Sibiraj-S** [comment]
merging #1044 + this PR will close #1045

**Comment by dherges** [comment]
Hi @Sibiraj-S , we ave noise in the package.json and lock file. Do you rebase this PR/replay changes on current master?

**Comment by Sibiraj-S** [comment]
One moment.

**Comment by Sibiraj-S** [comment]
@dherges. Resolved.

**Pull request merged**
