### PR TITLE
fix: add rollup commonjs plugin to support all library types

### PR DESCRIPTION
**Pull request by msusur**
## I'm submitting a...

- [X] Bug Fix
- [ ] Feature
- [ ] Other (Refactoring, Added tests, Documentation, ...)

## Checklist

- [X] Commit Messages follow the [Conventional Commits](https://conventionalcommits.org/) pattern, see current [`.vcmrc`](https://github.com/dherges/ng-packagr/blob/master/.vcmrc)
- [X] Tests for the changes have been added

## Description

This PR is to fix an issue that is described in the [issue #227](https://github.com/rollup/rollup-plugin-commonjs/issues/227).

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by dherges** [comment]
Hi Mert,

thank you for your effort!

Changes look good. It seems to not break existing builds (that's a good thing! :+1: 

Have you tested the changes with a commonjs dependency? I can't see any direct test case in the samples so that's why I am asking.

**Comment by msusur** [comment]
Yes, it works perfectly with [angular2-moment](https://github.com/urish/angular2-moment) whereas wasn't working before the change. This change helps automatically resolve the external dependencies for commonjs, otherwise you need to resolve it using the config. To be honest it isn't a big deal, but I think it would be nice to have this as a built in feature. What do you think @dherges ?

Workaround would be

```json
{
  "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
  "lib": {
    "entryFile": "src/public_api.ts",
    "externals": {
      "angular2-moment": "angular2-moment/module"
    }
  }
}
```

**Comment by dherges** [comment]
Checked that some existing builds do not break with current version. So I think it's good to go!

**Comment by dherges** [comment]
I squash this as "feat: <..>" to master ... maybe, technically it could also be a fix ... I don't know tbh and it feels a little bit more like a new feature to me???

**Comment by msusur** [comment]
Well I think it makes sense :)  @dherges 🍻

**Comment by dherges** [comment]
Fuck it... I found one use case where we broke an existing build (= regression caused)

Prior to `rollup-plugin-commonjs`,  it was possible to embed a bundled dependency and it would register to the global scope. Example:

source
```ts
/// <reference path="./keycloak.d.ts" />
import "keycloak-js";
```

Resulting bundle ("foo.es5.js"):

```js
(function (window, undefined) {
/* ... */
    if (typeof module === "object" && module && typeof module.exports === "object") {
        module.exports = Keycloak;
    }
    else {
        window.Keycloak = Keycloak;
        if (typeof define === "function" && define.amd) {
            define("keycloak", [], function () { return Keycloak; });
        }
    }
})(window);
```

Result: `window.Keycloak` is defined. It is intentionally wanted to embed that IIFE `(function() { })(window)` because a wrapper/adapter around a 3rd party lib is created....


Now, with `rollup-plugin-commonjs`:

```js
function createCommonjsModule(fn, module) {
    return module = { exports: {} }, fn(module, module.exports), module.exports;
}
var keycloak = createCommonjsModule(function (module) {
    (function (window, undefined) {
/* ... */

        if ('object' === "object" && module && 'object' === "object") {
            module.exports = Keycloak;
        }
        else {
            window.Keycloak = Keycloak;
            if (typeof undefined === "function" && undefined.amd) {
                undefined("keycloak", [], function () { return Keycloak; });
            }
        }

});
```

Result: `window.Keycloak` is undefined since "module.exports"  is passed to the bundled dependency.

Users were (of course!) relying on `window.Keycloak` and `window['Keycloak']`.

So question is: what is the TypeScript import syntax to obtain a reference to exported symbols of the bundled library?!?

**Comment by dherges** [comment]
Ok, the migration/solution in that very specific case is:

```ts
/// <reference path="./keycloak.d.ts" />
import "keycloak-js";
import * as Keycloak from 'keycloak-js'; // <-- added this import

const foo = new Keycloak();
```

Prior, the `new Keycloak()` call used to work because of the global-scoped stuff and `keycloak.d.ts` declaring that global variable....

**Comment by msusur** [comment]
Do you think there is a way to automate those tests? We could see that happening when I first created the PR, and saved you a lot of time :)

**Comment by dherges** [comment]
Hi @msusur,

it's possible to add an integration test. Either in one of the [existing samples](https://github.com/dherges/ng-packagr/tree/master/integration/samples) or add a new one.

**Pull request merged**
